model: CET 

emb_dim: 256
num_layers: 8
num_heads: 8
num_rbf: 64
rbf_type: expnorm
trainable_rbf: false # consider changing
neighbor_embedding: true
max_num_neighbors: 32
distance_influence: both

aggregation: add
activation: silu
cutoff_lower: 0.0
cutoff_upper: 5.0
derivative: false
max_z: 118

derivative: false
layernorm_on_vec: True
# reduce_op: add
# precision: 32

p_dropcond: 0.2 #0.2
p_droppath: 0.00

# use_cls_token: False
# norm_cls: True
# pred_cls: False 

use_cls_token: False
norm_cls: True
pred_cls: False 
emb_cls: False  
global_pos_emb: False

vector_cutoff: True  #TODO test this