model: CET 

emb_dim: 256
num_layers: 8
num_heads: 8
num_rbf: 64
rbf_type: expnorm
trainable_rbf: false 
neighbor_embedding: true
max_num_neighbors: 32 # 64 #32 # increase this if you run into errors using larger molecules
distance_influence: both

aggregation: add
activation: silu
cutoff_lower: 0.0
cutoff_upper: 5.0
derivative: false
max_z: 118

derivative: false
layernorm_on_vec: False

p_dropcond: 0.2 
p_droppath: 0.1 

inv_post_norm: True
vec_post_norm: False 
vec_prenorm: True
emb_agg : sum 
vector_cutoff: True 


