model: CET 

emb_dim: 128
num_layers: 6
num_heads: 8
num_rbf: 32
rbf_type: expnorm
trainable_rbf: false # consider changing
neighbor_embedding: true
max_num_neighbors: 32
distance_influence: both

aggregation: add
activation: silu
cutoff_lower: 0.0
cutoff_upper: 5.0
derivative: false
max_z: 118

derivative: True
layernorm_on_vec: True

p_dropcond: 0.2 #0.2
p_droppath: 0.1
# post_norm: False
inv_post_norm: False
vec_post_norm: False 
vec_prenorm: True

emb_agg : sum # TRY mean version

vector_cutoff: True  #TODO test this


