model: ET #equivariant-transformer

emb_dim: 256
num_layers: 8
num_heads: 8
num_rbf: 64
rbf_type: expnorm
trainable_rbf: false # consider changing
neighbor_embedding: true
max_num_neighbors: 32
distance_influence: both

aggregation: add
activation: silu
cutoff_lower: 0.0
cutoff_upper: 5.0
derivative: false
max_z: 118

derivative: false
layernorm_on_vec: True


use_cls_token: True
norm_cls: True
pred_cls: False # not as good for eng prediction 
emb_cls: False # TO BE TESTED
global_pos_emb: True

# model_dropout: 0.0 #1 #5
# model_droppath: 0.1 #1