

load_model: null
log_dir: experiments/

model_config: configs/model_configs/cet.yaml

## DATASET & LOADER INPUTS ###
dataset: MD17
dataset_root: tmp/md17
dataset_arg : aspirin
train_size: 950 #DEBUG
test_size: null
val_size: 50
batch_size: 128
inference_batch_size: 128
seed: 1
num_workers: 6


splits: null
standardize: true # multiply prediction by dataset std and add mean

denoising_only: False 
energy_weight: 1.0 # weight on y loss
force_weight: 1.0
ema_alpha_dy: 1.0
ema_alpha_y: 0.05 # FIXME: tesxt diff values
#TODO: set derivative
comp_derivative: true # turn on derivative computations TODO: add this to parser and training module
energy_wieght: 0.2 # TODO add
force_weight: 0.8

distributed_backend: ddp
early_stopping_patience: 1500
ngpus: -1
num_nodes: 1
redirect: false

lr: 0.001
lr_schedule: cosine
lr_factor: 0.8
lr_min: 1.0e-07
lr_patience: 30
lr_warmup_steps: 10000 
lr_cosine_length: 300000
num_epochs: 3000 # DEBUG
num_steps: 300000 #DEBUG
precision: 32

save_interval: 10
test_interval: 10

wandb_notes: ""
job_id: auto

pretraining: false
self_cond: True
weight_decay: 0.0

# data agumentations
random_rotate: True
torsion_angle_std: 0
max_bonds_rotated : 0
p_invert : 0.0
noise_scale: 0.00
denoising_weight: 0.1 #1 