
log_dir: experiments/
load_model: null
load_hf: null
# load_hf : ct-scd-pcq # load our pretrained model from hugging-face
job_id: qm9_homo
wandb_notes: ""

model_config: configs/model_configs/scd.yaml

## DATASET & LOADER INPUTS ###
dataset: QM9
dataset_root: tmp/qm9
dataset_arg : homo
train_size: 110000 #DEBUG
test_size: null
val_size: 10000
batch_size: 128
inference_batch_size: 128
seed: 1
num_workers: 6

splits: null
standardize: true # multiply prediction by dataset std and add mean

energy_weight: 1.0 # weight on y loss
force_weight: 1.0
ema_alpha_dy: 1.0
ema_alpha_y: 1.0

distributed_backend: ddp
ngpus: -1
num_nodes: 1
redirect: false

lr: 0.0005
lr_schedule: cosine
lr_factor: 0.8
lr_min: 1.0e-07
lr_patience: 15
lr_warmup_steps: 10000 
lr_cosine_length: 300000
num_epochs: 3000 # DEBUG
num_steps: 300000 #DEBUG
precision: 32

save_interval: 5 
test_interval: 1



pretraining: false
self_cond: false

weight_decay: 0.01
droppath_warmup: True
init_droppath: 0.15
final_droppath: 0.1
beta1: 0.995

momentum_update: False
model_momentum: 0.996
val_ema_model: False

# data agumentations
random_rotate: True
torsion_angle_std: 0
max_bonds_rotated : 0
p_invert : 0.0

noise_scale: 0.005
denoising_weight: 0.1

#fine tuning specific flags
reset_head: False
reset_embeddings: False
reset_norms: null 

parity_plot: True
plot_interval: 1

