load_model: null
log_dir: experiments/
job_id: scd-s-n004_pcq
wandb_notes: "SCD pretraining with PCQ"

## DATASET & LOADER INPUTS ###
dataset: PCQM4MV2
dataset_root: tmp/pcq
dataset_arg : null
train_size: null 

test_size: 100
val_size: 100
batch_size: 64
inference_batch_size: 64
seed: 1
num_workers: 6

#choose model architecture here
model_config: configs/model_configs/scd.yaml

energy_weight: 0.0
force_weight: 1.0
ema_alpha_dy: 1.0
ema_alpha_y: 1.0

distributed_backend: ddp
ngpus: -1
num_nodes: 1
redirect: false

lr: 0.0005 
weight_decay: 0.05
lr_schedule: cosine
lr_factor: 0.8
lr_min: 1.0e-07
lr_patience: 15
lr_warmup_steps: 10000 
lr_cosine_length: 800000 
num_epochs: 3000 
num_steps: 800000 
precision: 32

splits: null
standardize: false 

save_interval: 1
test_interval: 1

pretraining: true
self_cond: true
noise_scale: 0.04

noise_in_loader: False # Turn this to True if you want to run these models without compiling the torchnet graph kernal
allow_periodic: False # Turn this to True if you want to allow for periodic inputs

momentum_update: False
model_momentum: 0.996
val_ema_model: False

# data agumentations
random_rotate: False
torsion_angle_std: 0.0
max_bonds_rotated : 0
p_invert : 0.0

denoising_weight: 1.0 
droppath_warmup: False

parity_plot: False
plot_interval: 1

### use these inputs to clip batches if necessary to avoid OOM erros
# max_nodes_per_batch : 4000
# batch_clipper_cache_size : 1000