

load_model: null
log_dir: experiments/

model_config: configs/model_configs/scd.yaml

## DATASET & LOADER INPUTS ###
dataset: QM9
dataset_root: tmp/qm9
dataset_arg : u0
# dataset_arg : u0_atom
train_size: 110000 #DEBUG
test_size: null
val_size: 10000
batch_size: 128 #32 # for a total of 128 across 4 GPUs
inference_batch_size: 128 # 32
seed: 1
num_workers: 6

splits: null
standardize: False # multiply prediction by dataset std and add mean
# prior_model: Atomref
prior_model: LearnableAtomref

# standardize: True # multiply prediction by dataset std and add mean
# prior_model: null

denoising_only: False 
energy_weight: 1.0 # weight on y loss
force_weight: 1.0
ema_alpha_dy: 1.0
ema_alpha_y: 0.05
gradient_clipping: 3.0

distributed_backend: ddp
early_stopping_patience: 1500
ngpus: -1
num_nodes: 1
redirect: false

lr: 0.0003
# lr_schedule: reduce_on_plateau
lr_schedule: cosine
lr_factor: 0.8
lr_min: 1.0e-07
lr_patience: 15 #30
lr_warmup_steps: 15000 
lr_cosine_length: 500000
num_epochs: 3000 # DEBUG
num_steps: 500000 #DEBUG
precision: 32

save_interval: 10
test_interval: 2

wandb_notes: ""
job_id: auto

pretraining: false
self_cond: false

weight_decay: 0.01 # TESTING
weight_decay_on_head: False # TEST ON/OFF
droppath_warmup: true
init_droppath: 0.15
final_droppath: 0.0 # TEST ON/OFF
beta1: 0.995

momentum_update: False
model_momentum: 0.996
val_ema_model: False

# data agumentations
random_rotate: false
torsion_angle_std: 0
max_bonds_rotated : 0
p_invert : 0.0
noise_scale: 0.005
denoising_weight: 0.2

